FROM debian:stable-slim

WORKDIR /app

RUN apt-get -qq update \
  && apt-get -qq -y install curl zip unzip \
  && curl -fsSL https://deno.land/x/install/install.sh | sh \
  && apt-get -qq remove curl zip unzip

ENV DENO_INSTALL /root/.deno
ENV PATH $DENO_INSTALL/bin:$PATH
