version: "3.3"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "23000:3000"
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env
    tty: true

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "29999:9999"
    volumes:
      - ./api:/app
    tty: true
